import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import "./globals.css";

import { PropsWithChildren } from "react";
import { AppSidebar, Header } from "./_components";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedOut>
            <div className="flex justify-center items-center h-screen">
              <Card className="w-68 bg-gray-50 h-36 items-center justify-center">
                <CardContent className="flex w-full flex-col gap-4">
                  <SignInButton />
                  <SignUpButton>
                    <Button className="bg-black w-full text-white rounded-lg font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </Button>
                  </SignUpButton>
                </CardContent>
              </Card>
            </div>
          </SignedOut>

          <SignedIn>
            <div className="w-screen h-screen">
              <Header />

              <AppSidebar>{children}</AppSidebar>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
